services:
  app:
    build: .
    ports:
      - 8000:8000
  db:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=nol
      - MARIADB_PASSWORD=nol
      - MARIADB_DATABASE=meal_provider
    volumes:
      - database:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
volumes:
  database: