services:
  app:
    build: .
    image: ghcr.io/dd360870/mealprovider-app:latest
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DEBUG=1
      - FLASK_APP=flaskr
  db:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=nol
      - MARIADB_PASSWORD=nol
      - MARIADB_DATABASE=meal_provider
    volumes:
      - database:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 10s
      retries: 3
  redis:
    image: redis
  celery:
    environment:
      - DB_HOST=db
    image: ghcr.io/dd360870/mealprovider-app:latest
    command: celery -A make_celery worker --loglevel INFO
  celery-beat:
    image: ghcr.io/dd360870/mealprovider-app:latest
    command: celery -A make_celery beat --loglevel INFO

volumes:
  database:
