services:
  app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    tty: true
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=flaskr
      - FLASK_DEBUG=1
  celery:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=flaskr
    command: watchmedo auto-restart -d flaskr/ -p '*.py' -- celery -A make_celery worker --loglevel INFO